name: RISD
highlighter: pygments
safe: true
markdown: kramdown
exclude: ['scss',
          'Gemfil*',
          'Procfil*',
          '*.command',
          'README.md',
          'assets/style/scss/*']